<a href="https://colab.research.google.com/github/Iqra-kamil/Pythonclass/blob/main/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#handling issing values
import pandas as pd

data = {
    'Name': ['Ram','Kamal','Ajay'],
    'Age': [25,None,32],
    'Salary': [5000,6000,None]

}
df = pd.DataFrame(data)
print("Original dataframe")
#print(df)

df.isnull().sum()
#df.fillna(0)

#df.dropna()

print(df.isnull().sum()) # sum of null

df_drop = df.dropna()
print(df_drop)

# fillna
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
print(df)

Original dataframe


,0
Name,0
Age,1
Salary,1


In [ ]:
# encoding
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data = {
    'Name':['Ram','Kamal','Ajay','Neetu','Kavi','Sapu'],
    'Age':[25,None,32,20,21,22],
    'Salary':[5000,6000,None,7000,8000,9000],
    'Gender':['male','male','male',None,'female','female']
}

df = pd.DataFrame(data)
print("original dataframe")
print(df)

#labelencoder
le = LabelEncoder()
df_label = df.copy()
df_label['Gender'] = df['Gender'].fillna('unknown')
df_label['Gender_encoder'] = le.fit_transform(df_label['Gender'])
print('after label encoding: ')
print(df_label)

original dataframe
    Name   Age  Salary  Gender
0    Ram  25.0  5000.0    male
1  Kamal   NaN  6000.0    male
2   Ajay  32.0     NaN    male
3  Neetu  20.0  7000.0    None
4   Kavi  21.0  8000.0  female
5   Sapu  22.0  9000.0  female
after label encoding: 
    Name   Age  Salary   Gender  Gender_encoder
0    Ram  25.0  5000.0     male               1
1  Kamal   NaN  6000.0     male               1
2   Ajay  32.0     NaN     male               1
3  Neetu  20.0  7000.0  unknown               2
4   Kavi  21.0  8000.0   female               0
5   Sapu  22.0  9000.0   female               0


In [ ]:
#one hot encoding
import pandas as pd
data = {
    'colors':['red','blue','green','red','Blue']
}

df = pd.DataFrame(data)
print("original data")
print(df)


#one hot encoding
encoded_df = pd.get_dummies(df,columns=['colors'])
print("after one hot encoding")
print(encoded_df)

original data
  colors
0    red
1   blue
2  green
3    red
4   Blue
after one hot encoding
   colors_Blue  colors_blue  colors_green  colors_red
0        False        False         False        True
1        False         True         False       False
2        False        False          True       False
3        False        False         False        True
4         True        False         False       False


In [ ]:
# handle missing values
import pandas as pd
import numpy as np
data = {
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
print(df)

# handle missing values
import pandas as pd
import numpy as np
data = {
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
# print(df)

# handle null values
df.dropna(inplace=True)
print(df)


   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
6     NaN
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [ ]:
#label encoding
from sklearn.preprocessing import LabelEncoder

#methid 1
le = LabelEncoder()
df['colors_encoder1'] = le.fit_transform(df['colors'])

#method 2
df['colors_encoder2'] = LabelEncoder().fit_transform(df['colors'])
print(df)

#method 3
import sklearn
df['colors_encoder3'] = sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
print(df)

   colors  colors_encoder  colors_encoder2  colors_encoder1
0     red               3                3                3
1   green               1                1                1
2    blue               0                0                0
3  orange               2                2                2
4   green               1                1                1
5    blue               0                0                0
   colors  colors_encoder  colors_encoder2  colors_encoder1  colors_encoder3
0     red               3                3                3                3
1   green               1                1                1                1
2    blue               0                0                0                0
3  orange               2                2                2                2
4   green               1                1                1                1
5    blue               0                0                0                0


In [ ]:
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder' in df.keys():
  df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding(by the help of pandas)
df_encoder = pd.get_dummies(df,columns=['colors'])
print(df_encoder)


   colors  colors_encoder  colors_encoder2  colors_encoder1  colors_encoder3
0     red               3                3                3                3
1   green               1                1                1                1
2    blue               0                0                0                0
3  orange               2                2                2                2
4   green               1                1                1                1
5    blue               0                0                0                0
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors_blue  colors_green  colors_orange  colors_red
0        False         False          False        True
1        False          True          False       False
2         True         False          False       False
3        False         False           True       False
4        False          True          False       False
5         True         False          False       False

In [ ]:
# combination of handle missing value | label encoding | onehot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

data = {
    "age":[10,20,np.nan,26,30],
    "gender":['male','female','others','male',np.nan],
    "name":['dheeraj','kavi','sapu','yash','hello']
}

df = pd.DataFrame(data)

# handle missing values
df['age'] = df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'],inplace=True)
print(df)

# label encoding
le = LabelEncoder()
df['gender1'] = le.fit_transform(df['gender'])
print(df)

# one hot encoding
oe = OneHotEncoder()
oe_e = oe.fit_transform(df[['gender']]).toarray()
print(oe_e)

    age  gender     name
0  10.0    male  dheeraj
1  20.0  female     kavi
2  21.5  others     sapu
3  26.0    male     yash
    age  gender     name  gender1
0  10.0    male  dheeraj        1
1  20.0  female     kavi        0
2  21.5  others     sapu        2
3  26.0    male     yash        1
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
